import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toast, ToastProvider } from "@/components/ui/toast";

const poppins = Poppins({ subsets: ["latin"], weight:['300', '400', '500'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>{children}</main>
        <ToastProvider>
          <Toast />
        </ToastProvider>
      </body>
    </html>
  );
}
